import type { Memory, SpaceInfo } from "@/types/memory";

export const MOCK_SPACE_ID = "a1b2c3d4-e5f6-7890-abcd-ef1234567890";

export const mockSpaceInfo: SpaceInfo = {
  tenant_id: MOCK_SPACE_ID,
  name: "",
  status: "active",
  provider: "tidb_zero",
  memory_count: 42,
  created_at: "2025-11-15T08:30:00Z",
};

const now = new Date();
const hoursAgo = (h: number) =>
  new Date(now.getTime() - h * 3_600_000).toISOString();
const daysAgo = (d: number) =>
  new Date(now.getTime() - d * 86_400_000).toISOString();

export const mockMemories: Memory[] = [
  // ── Recent (within 7 days) ──
  {
    id: "mem-001",
    content:
      "I prefer TypeScript over JavaScript for all projects. I dislike Java and avoid it when possible.",
    memory_type: "pinned",
    source: "openclaw",
    tags: ["preference", "language"],
    metadata: { facet: "preferences" },
    agent_id: "agent",
    session_id: "sess-abc-001",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: daysAgo(5),
    updated_at: hoursAgo(2),
  },
  {
    id: "mem-002",
    content:
      "用户正在开发一个叫 mem9 的 AI agent 记忆系统，后端用 Go，前端用 React + TypeScript。这是核心项目，几乎所有对话都围绕这个展开。",
    memory_type: "insight",
    source: "openclaw",
    tags: ["project", "context"],
    metadata: { facet: "about_you", extracted_from: "conversation", confidence: 0.92 },
    agent_id: "agent",
    session_id: "sess-abc-002",
    state: "active",
    version: 2,
    updated_by: "agent",
    created_at: daysAgo(10),
    updated_at: daysAgo(1),
  },
  {
    id: "mem-003",
    content: "Dark mode is always preferred. Light themes cause eye strain.",
    memory_type: "insight",
    source: "openclaw",
    tags: ["preference", "ui"],
    metadata: { facet: "preferences" },
    agent_id: "agent",
    session_id: "sess-abc-003",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
  },
  {
    id: "mem-019",
    content:
      "Dashboard MVP 定位：不是记忆分析后台，是「我的长期记忆空间」。两页方案：Connect + Your Memory。面向普通用户，不面向开发者。",
    memory_type: "insight",
    source: "openclaw",
    tags: ["project", "dashboard"],
    metadata: { facet: "plans" },
    agent_id: "agent",
    session_id: "sess-abc-015",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: hoursAgo(3),
    updated_at: hoursAgo(3),
  },
  {
    id: "mem-011",
    content:
      "用户对产品文档的要求：先中文写 spec，再根据需要翻译。文档语气要求直接、不神化技术。",
    memory_type: "insight",
    source: "openclaw",
    tags: ["preference", "documentation"],
    metadata: { facet: "preferences" },
    agent_id: "agent",
    session_id: "sess-abc-009",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    id: "mem-010",
    content:
      "Tailwind CSS is the preferred styling approach. Avoid CSS-in-JS. Use shadcn/ui components when possible.",
    memory_type: "pinned",
    source: "openclaw",
    tags: ["preference", "css"],
    metadata: { facet: "preferences" },
    agent_id: "agent",
    session_id: "sess-abc-008",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: daysAgo(4),
    updated_at: daysAgo(4),
  },
  {
    id: "mem-014",
    content:
      "Save Room（回忆小屋）是 mem9 的创意可视化项目，JRPG 像素风。作为 Labs 彩蛋存在，不是主线产品。",
    memory_type: "insight",
    source: "openclaw",
    tags: ["project", "pixel-art"],
    metadata: { facet: "plans" },
    agent_id: "agent",
    session_id: "sess-abc-011",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  // ── Within 30 days ──
  {
    id: "mem-004",
    content:
      "项目代号 mem9，全称 mnemos。产品定位是给 AI coding agent 做持久记忆。当前已接入 OpenClaw、OpenCode、Claude Code 三个平台。",
    memory_type: "pinned",
    source: "openclaw",
    tags: ["project", "naming"],
    metadata: { facet: "about_you" },
    agent_id: "agent",
    session_id: "sess-abc-004",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: daysAgo(14),
    updated_at: daysAgo(7),
  },
  {
    id: "mem-005",
    content:
      "When writing Go code, use three import groups: stdlib, external, internal. Always use gofmt. Acronyms stay all-caps: tenantID, agentID.",
    memory_type: "insight",
    source: "claude-code",
    tags: ["coding-style", "go"],
    metadata: { facet: "routines", extracted_from: "code_review", confidence: 0.88 },
    agent_id: "claude",
    session_id: "sess-cc-001",
    state: "active",
    version: 1,
    updated_by: "claude",
    created_at: daysAgo(8),
    updated_at: daysAgo(8),
  },
  {
    id: "mem-006",
    content:
      "用户的工作时间通常是早上 9 点到晚上 11 点，周末也经常工作。沟通偏好中文，但技术文档接受英文。",
    memory_type: "insight",
    source: "openclaw",
    tags: ["schedule", "preference"],
    metadata: { facet: "routines" },
    agent_id: "agent",
    session_id: "sess-abc-005",
    state: "active",
    version: 3,
    updated_by: "agent",
    created_at: daysAgo(20),
    updated_at: daysAgo(8),
  },
  {
    id: "mem-008",
    content:
      "The TiDB database is the primary backend. Vector search uses VEC_COSINE_DISTANCE. Full-text search uses fts_match_word with BM25. Both are merged via RRF (k=60).",
    memory_type: "insight",
    source: "opencode",
    tags: ["architecture", "search"],
    metadata: { facet: "about_you", extracted_from: "code_exploration", confidence: 0.95 },
    agent_id: "opencode-agent",
    session_id: "sess-oc-001",
    state: "active",
    version: 1,
    updated_by: "opencode-agent",
    created_at: daysAgo(11),
    updated_at: daysAgo(11),
  },
  {
    id: "mem-012",
    content:
      "ESM only for TypeScript packages. Always use .js extensions on local imports with NodeNext resolution. Use import type for type-only imports.",
    memory_type: "insight",
    source: "claude-code",
    tags: ["coding-style", "typescript"],
    metadata: { facet: "routines", extracted_from: "code_review", confidence: 0.91 },
    agent_id: "claude",
    session_id: "sess-cc-002",
    state: "active",
    version: 1,
    updated_by: "claude",
    created_at: daysAgo(9),
    updated_at: daysAgo(9),
  },
  {
    id: "mem-009",
    content:
      "部署环境用 Kubernetes。API 域名是 api.mem9.ai，官网是 mem9.ai，用 Astro 构建。",
    memory_type: "insight",
    source: "openclaw",
    tags: ["infrastructure", "deployment"],
    metadata: { facet: "about_you" },
    agent_id: "agent",
    session_id: "sess-abc-007",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: daysAgo(12),
    updated_at: daysAgo(12),
  },
  {
    id: "mem-015",
    content:
      "用户的 agent 配置：OpenClaw 是主力日常 agent，Claude Code 用于深度代码审查，OpenCode 偶尔使用。三者共享同一个 mem9 space。",
    memory_type: "insight",
    source: "openclaw",
    tags: ["setup", "agent"],
    metadata: { facet: "about_you" },
    agent_id: "agent",
    session_id: "sess-abc-012",
    state: "active",
    version: 2,
    updated_by: "agent",
    created_at: daysAgo(11),
    updated_at: daysAgo(10),
  },
  // ── Within 90 days ──
  {
    id: "mem-007",
    content:
      "Always respond in Chinese for agent mode, plan mode, debug mode and ask mode, but not for git commit messages.",
    memory_type: "pinned",
    source: "openclaw",
    tags: ["rule", "language"],
    metadata: { facet: "constraints" },
    agent_id: "agent",
    session_id: "sess-abc-006",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: daysAgo(45),
    updated_at: daysAgo(45),
  },
  {
    id: "mem-013",
    content: "No ORM. Use raw database/sql with parameter placeholders only.",
    memory_type: "pinned",
    source: "openclaw",
    tags: ["rule", "database"],
    metadata: { facet: "constraints" },
    agent_id: "agent",
    session_id: "sess-abc-010",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: daysAgo(60),
    updated_at: daysAgo(60),
  },
  {
    id: "mem-016",
    content:
      "Error handling pattern: sentinel errors in domain/errors.go, compare with errors.Is(), wrap with fmt.Errorf context: %w.",
    memory_type: "insight",
    source: "claude-code",
    tags: ["coding-style", "go", "error-handling"],
    metadata: { facet: "routines", extracted_from: "code_review", confidence: 0.89 },
    agent_id: "claude",
    session_id: "sess-cc-003",
    state: "active",
    version: 1,
    updated_by: "claude",
    created_at: daysAgo(35),
    updated_at: daysAgo(35),
  },
  {
    id: "mem-018",
    content:
      "Don't add comments that just narrate what the code does. Comments should only explain non-obvious intent, trade-offs, or constraints.",
    memory_type: "pinned",
    source: "openclaw",
    tags: ["rule", "coding-style"],
    metadata: { facet: "constraints" },
    agent_id: "agent",
    session_id: "sess-abc-014",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: daysAgo(50),
    updated_at: daysAgo(50),
  },
  // ── Older than 90 days ──
  {
    id: "mem-017",
    content: "周末喜欢打羽毛球，偶尔跑步。工作日久坐较多，需要提醒休息。",
    memory_type: "insight",
    source: "openclaw",
    tags: ["personal", "health"],
    metadata: { facet: "experiences" },
    agent_id: "agent",
    session_id: "sess-abc-013",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: daysAgo(120),
    updated_at: daysAgo(120),
  },
  {
    id: "mem-020",
    content:
      "INSERT ... ON DUPLICATE KEY UPDATE is the expected upsert pattern. Atomic version bump: SET version = version + 1.",
    memory_type: "insight",
    source: "opencode",
    tags: ["coding-style", "sql"],
    metadata: { facet: "routines" },
    agent_id: "opencode-agent",
    session_id: "sess-oc-002",
    state: "active",
    version: 1,
    updated_by: "opencode-agent",
    created_at: daysAgo(100),
    updated_at: daysAgo(100),
  },
  {
    id: "mem-021",
    content:
      "Alice is the co-founder and handles product strategy. Bob leads backend infrastructure. They both have access to the shared mem9 space.",
    memory_type: "insight",
    source: "openclaw",
    tags: ["team", "people"],
    metadata: { facet: "important_people" },
    agent_id: "agent",
    session_id: "sess-abc-016",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: daysAgo(25),
    updated_at: daysAgo(25),
  },
  {
    id: "mem-022",
    content:
      "每周五下午是团队 demo 时间，不安排深度编码。周三晚上通常是跑步日。",
    memory_type: "insight",
    source: "openclaw",
    tags: ["schedule", "routine"],
    metadata: { facet: "routines" },
    agent_id: "agent",
    session_id: "sess-abc-017",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: daysAgo(18),
    updated_at: daysAgo(18),
  },
  {
    id: "mem-023",
    content:
      "Q2 plan: launch dashboard MVP, integrate with 2 more agent platforms, reach 100 active spaces.",
    memory_type: "pinned",
    source: "openclaw",
    tags: ["plan", "roadmap"],
    metadata: { facet: "plans" },
    agent_id: "agent",
    session_id: "sess-abc-018",
    state: "active",
    version: 1,
    updated_by: "agent",
    created_at: daysAgo(15),
    updated_at: daysAgo(15),
  },
  {
    id: "mem-024",
    content:
      "Never commit .env files with real credentials. Use .env.local for secrets and keep .env for safe defaults only.",
    memory_type: "pinned",
    source: "claude-code",
    tags: ["rule", "security"],
    metadata: { facet: "constraints" },
    agent_id: "claude",
    session_id: "sess-cc-004",
    state: "active",
    version: 1,
    updated_by: "claude",
    created_at: daysAgo(40),
    updated_at: daysAgo(40),
  },
];
